// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQs98IRNfeJ1v0LRvRqZq9Bo8EJjDEY0Q',
    appId: '1:642694559072:android:49df85c1d7be7e27a41a05',
    messagingSenderId: '642694559072',
    projectId: 'selamkapisi-75abb',
    storageBucket: 'selamkapisi-75abb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcHo74r-AmXPeceWklwrSQM-wL-YOfdec',
    appId: '1:642694559072:ios:8f94c37bf2b6a76da41a05',
    messagingSenderId: '642694559072',
    projectId: 'selamkapisi-75abb',
    storageBucket: 'selamkapisi-75abb.firebasestorage.app',
    androidClientId: '642694559072-otjot778vqpbld4rhbap8ajgafju7j72.apps.googleusercontent.com',
    iosClientId: '642694559072-t1648dmb9cfhohfofmf1g9dallu0mv51.apps.googleusercontent.com',
    iosBundleId: 'com.example.selamkapisi',
  );
}
